# Generated by Django 4.2.7 on 2024-12-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(max_length=500),
        ),
    ]
